-- gets an aircraft model receiving their model name and the project
CREATE OR REPLACE FUNCTION FC_GET_AIRCRAFT_MODEL (L_MODEL_NAME IN VARCHAR, L_ID_PROJECT IN INTEGER)
RETURN SYS_REFCURSOR
IS
  C1 SYS_REFCURSOR;
BEGIN
  OPEN C1 FOR
  SELECT  AM.ID_AIRCRAFT_MODEL, AM.MODEL_NAME, AM.DESCRIPTION, AM.MAKER,
          AM.AIRCRAFT_TYPE, M.MOTOR, M.NUMBER_MOTORS, M.MOTOR_TYPE,
          M.CRUISE_ALTITUDE, M.CRUISE_SPEED, M.TSFC, M.LAPSE_RATE_FACTOR,
          T.THRUST_0, T.THRUST_MAX_SPEED, T.MAX_SPEED, AM.EMPTY_WEIGHT,
          AM.MTOW, AM.MAX_PAYLOAD, AM.FUEL_CAPACITY, AM.VMO,
          AM.MMO, AM.WING_AREA, AM.WING_SPAN, AM.ASPECT_RATIO,
          AM.E
  FROM AIRCRAFT_MODEL AM, MOTORIZATION M, THRUST_FUNCTION T
  WHERE AM.ID_MOTORIZATION = M.ID_MOTORIZATION
  AND M.ID_THRUST_FUNCTION = T.ID_THRUST_FUNCTION
  AND AM.MODEL_NAME = L_MODEL_NAME
  AND AM.ID_PROJECT = L_ID_PROJECT;
  
  RETURN C1;
  
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Too many rows'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/

-- gets all aircraft models from a project
CREATE OR REPLACE FUNCTION FC_GET_AIRCRAFT_MODELS (L_ID_PROJECT IN INTEGER)
RETURN SYS_REFCURSOR
IS
  C1 SYS_REFCURSOR;
BEGIN
  OPEN C1 FOR
  SELECT  AM.ID_AIRCRAFT_MODEL, AM.MODEL_NAME, AM.DESCRIPTION, AM.MAKER,
          AM.AIRCRAFT_TYPE, M.MOTOR, M.NUMBER_MOTORS, M.MOTOR_TYPE,
          M.CRUISE_ALTITUDE, M.CRUISE_SPEED, M.TSFC, M.LAPSE_RATE_FACTOR,
          T.THRUST_0, T.THRUST_MAX_SPEED, T.MAX_SPEED, AM.EMPTY_WEIGHT,
          AM.MTOW, AM.MAX_PAYLOAD, AM.FUEL_CAPACITY, AM.VMO,
          AM.MMO, AM.WING_AREA, AM.WING_SPAN, AM.ASPECT_RATIO,
          AM.E
  FROM AIRCRAFT_MODEL AM, MOTORIZATION M, THRUST_FUNCTION T
  WHERE AM.ID_MOTORIZATION = M.ID_MOTORIZATION
  AND M.ID_THRUST_FUNCTION = T.ID_THRUST_FUNCTION
  AND AM.ID_PROJECT = L_ID_PROJECT;
  
  RETURN C1;
  
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Too many rows'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/

-- gets all aircraft models from a project
CREATE OR REPLACE FUNCTION FC_GET_CDRAG_FUNCTION (L_ID_AIRCRAFT_MODEL IN INTEGER)
RETURN SYS_REFCURSOR
IS
  C1 SYS_REFCURSOR;
BEGIN
  OPEN C1 FOR
  SELECT CDRAG_0, SPEED
  FROM CDRAG_FUNCTION
  WHERE ID_AIRCRAFT_MODEL = L_ID_AIRCRAFT_MODEL;
  
  RETURN C1;
  
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Too many rows'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/