CREATE TABLE T1 (
  T1C INTEGER PRIMARY KEY
);

CREATE TABLE T2 (
  T2C INTEGER PRIMARY KEY,
  T1C INTEGER NOT NULL REFERENCES T1(T1C) ON DELETE CASCADE
);

CREATE TABLE T3 (
  T3C INTEGER PRIMARY KEY,
  T2C INTEGER NOT NULL REFERENCES T2(T2C) ON DELETE CASCADE
);

INSERT INTO T1 VALUES (1);
INSERT INTO T2 VALUES (2, 1);
INSERT INTO T3 VALUES (3, 2);

SELECT * FROM T1;
SELECT * FROM T2;
SELECT * FROM T3;

DELETE FROM T1 WHERE T1C = 1;

SELECT * FROM T1;
SELECT * FROM T2;
SELECT * FROM T3;

DROP TABLE T3;
DROP TABLE T2;
DROP TABLE T1;