CREATE OR REPLACE FUNCTION FC_GET_FLIGHT_SIMULATIONS
  (L_ID_PROJECT IN INTEGER)
RETURN SYS_REFCURSOR
IS
  C1 SYS_REFCURSOR;
BEGIN
  OPEN C1 FOR
  SELECT  FS.ID_FLIGHT_SIMULATION, FI.DESIGNATOR, FS.SCHEDULED_ARRIVAL,
          FS.DEPARTURE_DATE, FS.EFFECTIVE_CREW, FS.EFFECTIVE_CARGO,
          FS.EFFECTIVE_FUEL
  FROM  FLIGHT_SIMULATION FS, FLIGHT_INFO FI
  WHERE FS.ID_FLIGHT_INFO = FI.ID_FLIGHT_INFO
    AND FS.ID_PROJECT = L_ID_PROJECT;

  RETURN C1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Too many rows'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/

--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION FC_GET_FLIGHT_SIMULATION
  (L_ID_PROJECT IN INTEGER, L_ID_FLIGHT_SIMULATION IN INTEGER)
RETURN SYS_REFCURSOR
IS
  C1 SYS_REFCURSOR;
BEGIN
  OPEN C1 FOR
  SELECT  FS.ID_FLIGHT_SIMULATION, FI.DESIGNATOR, FS.SCHEDULED_ARRIVAL,
          FS.DEPARTURE_DATE, FS.EFFECTIVE_CREW, FS.EFFECTIVE_CARGO,
          FS.EFFECTIVE_FUEL
  FROM  FLIGHT_SIMULATION FS, FLIGHT_INFO FI
  WHERE FS.ID_FLIGHT_INFO = FI.ID_FLIGHT_INFO
    AND FS.ID_PROJECT = L_ID_PROJECT
    AND FS.ID_FLIGHT_SIMULATION = L_ID_FLIGHT_SIMULATION;

  RETURN C1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Too many rows'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/

--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION FC_GET_AIRCRAFT_CLASS
  (L_ID_FLIGHT_SIMULATION IN INTEGER)
RETURN SYS_REFCURSOR
IS
  C1 SYS_REFCURSOR;
BEGIN
  OPEN C1 FOR
  SELECT  NUMBER_PASSENGERS
  FROM  AIRCRAFT_CLASS
  WHERE ID_FLIGHT_SIMULATION = L_ID_FLIGHT_SIMULATION;

  RETURN C1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Too many rows'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/

--------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION FC_GET_FLIGHT_PLAN
  (L_ID_FLIGHT_SIMULATION IN INTEGER)
RETURN SYS_REFCURSOR
IS
  C1 SYS_REFCURSOR;
BEGIN
  OPEN C1 FOR
  SELECT  S.SEGMENT_CODE, FP.SEGMENT_ORDER
  FROM  FLIGHT_PLAN FP, SEGMENT S
  WHERE FP.ID_SEGMENT = S.ID_SEGMENT
    AND FP.ID_FLIGHT_SIMULATION = L_ID_FLIGHT_SIMULATION;

  RETURN C1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Too many rows'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/