-- Authors
--
-- Daniel Gonçalves - 1151452
-- Eric Amaral - 1141570
-- Ivo Ferro - 1151159
-- Tiago Correia - 1151031

-- get all projects
CREATE OR REPLACE FUNCTION FC_GET_PROJECTS
RETURN SYS_REFCURSOR
IS
  C1 SYS_REFCURSOR;
BEGIN
  OPEN C1 FOR
  SELECT ID_PROJECT, NAME, DESCRIPTION
  FROM PROJECT;
  
  RETURN C1;
  
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Too many rows'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/

----------------------------------------------------------

-- function that receives the latitude and longitude of a coordinate and returns its ID
CREATE OR REPLACE FUNCTION FC_GET_ID_COORDINATE 
(PARAM_LATITUDE IN FLOAT, PARAM_LONGITUDE IN FLOAT, PARAM_ID_PROJECT IN INTEGER) 
RETURN VARCHAR IS ID_COORDINATE_RET VARCHAR(25);

BEGIN

  SELECT c.ID_COORDINATE INTO ID_COORDINATE_RET
  FROM COORDINATE c
  WHERE c.LATITUDE = PARAM_LATITUDE 
  AND c.LONGITUDE = PARAM_LONGITUDE
  AND c.ID_PROJECT = PARAM_ID_PROJECT;
  
  RETURN ID_COORDINATE_RET;
 
 EXCEPTION
   WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
   WHEN TOO_MANY_ROWS THEN
     DBMS_OUTPUT.PUT_LINE('Too many rows'||SYSDATE);
   WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
     
END FC_GET_ID_COORDINATE;

