-- Authors
--
-- Daniel Gonçalves - 1151452
-- Eric Amaral - 1141570
-- Ivo Ferro - 1151159
-- Tiago Correia - 1151031

-- Procedure that creates an aircraft model into a given project
CREATE OR REPLACE PROCEDURE PC_CREATE_AIRCRAFT_MODEL
  (L_ID_PROJECT IN INTEGER, -- project to be inserted in
  L_ID_AIRCRAFT_MODEL IN VARCHAR,
  L_DESCRIPTION IN VARCHAR,
  L_MAKER IN VARCHAR,
  L_AIRCRAFT_TYPE IN VARCHAR,
  L_MOTOR IN VARCHAR,
  L_NUMBER_MOTORS IN INTEGER,
  L_MOTOR_TYPE IN VARCHAR,
  L_CRUISE_ALTITUDE IN DOUBLE PRECISION,
  L_CRUISE_SPEED IN DOUBLE PRECISION,
  L_TSFC IN DOUBLE PRECISION,
  L_LAPSE_RATE_FACTOR IN DOUBLE PRECISION,
  L_THRUST_0 IN DOUBLE PRECISION,
  L_THRUST_MAX_SPEED IN DOUBLE PRECISION,
  L_MAX_SPEED IN DOUBLE PRECISION,
  L_EMPTY_WEIGHT IN DOUBLE PRECISION,
  L_MTOW IN DOUBLE PRECISION,
  L_MAX_PAYLOAD IN DOUBLE PRECISION,
  L_FUEL_CAPACITY IN DOUBLE PRECISION,
  L_VMO IN DOUBLE PRECISION,
  L_MMO IN DOUBLE PRECISION,
  L_WING_AREA IN DOUBLE PRECISION,
  L_WING_SPAN IN DOUBLE PRECISION,
  L_ASPECT_RATIO IN DOUBLE PRECISION,
  L_E IN DOUBLE PRECISION)
IS
  L_ID_THRUST_FUNCTION INTEGER;
BEGIN
  -- Insert thrust function
  INSERT INTO THRUST_FUNCTION (THRUST_0, THRUST_MAX_SPEED, MAX_SPEED)
  VALUES (L_THRUST_0, L_THRUST_MAX_SPEED, L_MAX_SPEED)
  RETURNING ID_THRUST_FUNCTION
  INTO L_ID_THRUST_FUNCTION;
  
  -- Insert motorization
  INSERT INTO MOTORIZATION
  (MOTOR, NUMBER_MOTORS, MOTOR_TYPE, CRUISE_ALTITUDE, CRUISE_SPEED,
  TSFC, LAPSE_RATE_FACTOR, ID_THRUST_FUNCTION)
  VALUES
  (L_MOTOR, L_NUMBER_MOTORS, L_MOTOR_TYPE, L_CRUISE_ALTITUDE, L_CRUISE_SPEED,
  L_TSFC, L_LAPSE_RATE_FACTOR, L_ID_THRUST_FUNCTION);
  
  -- Insert aircraft model
  INSERT INTO AIRCRAFT_MODEL
  (ID_PROJECT, ID_AIRCRAFT_MODEL, DESCRIPTION, MAKER, AIRCRAFT_TYPE, 
  MOTOR, EMPTY_WEIGHT, MTOW, MAX_PAYLOAD, FUEL_CAPACITY, VMO, MMO, WING_AREA, 
  WING_SPAN, ASPECT_RATIO, E)
  VALUES
  (L_ID_PROJECT, L_ID_AIRCRAFT_MODEL, L_DESCRIPTION, L_MAKER, L_AIRCRAFT_TYPE, 
  L_MOTOR, L_EMPTY_WEIGHT, L_MTOW, L_MAX_PAYLOAD, L_FUEL_CAPACITY, L_VMO, L_MMO,
  L_WING_AREA, L_WING_SPAN, L_ASPECT_RATIO, L_E);
  
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Too many rows'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/

-- Procedure that creates a cdrag function
CREATE OR REPLACE PROCEDURE PC_CREATE_CDRAG_FUNCTION
  (L_CDRAG_0 IN DOUBLE PRECISION,
  L_SPEED IN DOUBLE PRECISION,
  L_ID_AIRCRAFT_MODEL IN VARCHAR)
IS
BEGIN
  INSERT INTO CDRAG_FUNCTION (CDRAG_0, SPEED, ID_AIRCRAFT_MODEL)
  VALUES (L_CDRAG_0, L_SPEED, L_ID_AIRCRAFT_MODEL);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Too many rows'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/

-- Procedure that creates an empty project
CREATE OR REPLACE PROCEDURE PC_CREATE_EMPTY_PROJECT
  (L_ID_PROJECT OUT INTEGER, L_NAME OUT VARCHAR, L_DESCRIPTION OUT VARCHAR) IS
BEGIN
  INSERT INTO PROJECT (NAME, DESCRIPTION)
  VALUES ('Empty project', 'This is an empty project')
  RETURNING ID_PROJECT, NAME, DESCRIPTION
  INTO L_ID_PROJECT, L_NAME, L_DESCRIPTION;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Too many rows'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/

-- Procedure that deletes a project
CREATE OR REPLACE PROCEDURE PC_DELETE_PROJECT (L_ID_PROJECT IN INTEGER) IS
BEGIN
  DELETE FROM PROJECT WHERE ID_PROJECT = L_ID_PROJECT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/

-- Procedure that edits a project name and description
CREATE OR REPLACE PROCEDURE PC_EDIT_PROJECT_N_D
  (L_ID_PROJECT IN INTEGER, L_NEW_NAME IN VARCHAR, L_NEW_DESCRIPTION IN VARCHAR)
IS
BEGIN
  UPDATE PROJECT
  SET NAME = L_NEW_NAME, DESCRIPTION = L_NEW_DESCRIPTION
  WHERE ID_PROJECT = L_ID_PROJECT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('There was no data found'||SYSDATE);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occured'||SYSDATE);
END;
/ 