-- ### DELETE TABLES ###

DROP TABLE CDRAG_FUNCTION;
DROP TABLE AIRCRAFT_MODEL;
DROP TABLE AIRCRAFT_TYPE;
DROP TABLE MOTORIZATION;
DROP TABLE THRUST_FUNCTION;
DROP TABLE MOTOR_TYPE;
DROP TABLE PROJECT;

-- ### CREATE TABLES ###

CREATE TABLE PROJECT (
  ID_PROJECT INTEGER PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(150)
);

CREATE TABLE MOTOR_TYPE (
  TYPE VARCHAR(25) PRIMARY KEY
);

CREATE TABLE THRUST_FUNCTION (
  ID_THRUST_FUNCTION INTEGER PRIMARY KEY,
  THRUST_0 DOUBLE PRECISION NOT NULL,
  THRUST_MAX_SPEED DOUBLE PRECISION NOT NULL,
  MAX_SPEED DOUBLE PRECISION NOT NULL
);

CREATE TABLE MOTORIZATION (
  MOTOR VARCHAR(50) PRIMARY KEY,
  NUMBER_MOTORS INTEGER NOT NULL,
  MOTOR_TYPE VARCHAR(25) NOT NULL REFERENCES MOTOR_TYPE(TYPE),
  CRUISE_ALTITUDE DOUBLE PRECISION NOT NULL,
  CRUISE_SPEED DOUBLE PRECISION NOT NULL,
  TSFC DOUBLE PRECISION NOT NULL,
  LAPSE_RATE_FACTOR DOUBLE PRECISION NOT NULL,
  ID_THRUST_FUNCTION INTEGER NOT NULL REFERENCES THRUST_FUNCTION(ID_THRUST_FUNCTION)
);

CREATE TABLE AIRCRAFT_TYPE (
  TYPE VARCHAR(25) PRIMARY KEY
);

CREATE TABLE AIRCRAFT_MODEL (
  ID_AIRCRAFT_MODEL VARCHAR(25) PRIMARY KEY,
  DESCRIPTION VARCHAR(150) NOT NULL,
  MAKER VARCHAR(50) NOT NULL,
  AIRCRAFT_TYPE VARCHAR(25) NOT NULL REFERENCES AIRCRAFT_TYPE(TYPE),
  MOTOR VARCHAR(50) NOT NULL REFERENCES MOTORIZATION(MOTOR),
  EMPTY_WEIGHT DOUBLE PRECISION NOT NULL,
  MTOW DOUBLE PRECISION NOT NULL,
  MAX_PAYLOAD DOUBLE PRECISION NOT NULL,
  FUEL_CAPACITY DOUBLE PRECISION NOT NULL,
  VMO DOUBLE PRECISION NOT NULL,
  MMO DOUBLE PRECISION NOT NULL,
  WING_AREA DOUBLE PRECISION NOT NULL,
  WING_SPAN DOUBLE PRECISION NOT NULL,
  ASPECT_RATIO DOUBLE PRECISION NOT NULL,
  E DOUBLE PRECISION NOT NULL,
  ID_PROJECT INTEGER NOT NULL REFERENCES PROJECT(ID_PROJECT)
);

CREATE TABLE CDRAG_FUNCTION (
  CDRAG_0 DOUBLE PRECISION NOT NULL,
  SPEED DOUBLE PRECISION NOT NULL,
  ID_AIRCRAFT_MODEL VARCHAR(25) NOT NULL REFERENCES AIRCRAFT_MODEL(ID_AIRCRAFT_MODEL),
  CONSTRAINT PK_CDRAG_FUNCTION PRIMARY KEY (CDRAG_0, SPEED, ID_AIRCRAFT_MODEL)
);