-- Authors
--
-- Daniel Gonçalves - 1151452
-- Eric Amaral - 1141570
-- Ivo Ferro - 1151159
-- Tiago Correia - 1151031

-- ### DELETE TABLES ###

DROP TABLE FLIGHT_PLAN;
DROP TABLE AIRCRAFT_CLASS;
DROP TABLE FLIGHT_SIMULATION;
DROP TABLE WAYPOINT;
DROP TABLE FLIGHT_STOP;
DROP TABLE FLIGHT_INFO;
DROP TABLE FLIGHT_TYPE;
DROP TABLE CLASS;
DROP TABLE AIRCRAFT;
DROP TABLE STOP;
DROP TABLE AIRPORT;
DROP TABLE COORDINATE;
DROP TABLE SEGMENT;
DROP TABLE CDRAG_FUNCTION;
DROP TABLE AIRCRAFT_MODEL;
DROP TABLE AIRCRAFT_TYPE;
DROP TABLE MOTORIZATION;
DROP TABLE THRUST_FUNCTION;
DROP TABLE MOTOR_TYPE;
DROP TABLE PROJECT;

-- ### CREATE TABLES ###

CREATE TABLE PROJECT (
  ID_PROJECT INTEGER PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(150)
);

CREATE TABLE MOTOR_TYPE (
  TYPE VARCHAR(25) PRIMARY KEY
);

CREATE TABLE THRUST_FUNCTION (
  ID_THRUST_FUNCTION INTEGER PRIMARY KEY,
  THRUST_0 DOUBLE PRECISION NOT NULL,
  THRUST_MAX_SPEED DOUBLE PRECISION NOT NULL,
  MAX_SPEED DOUBLE PRECISION NOT NULL
);

CREATE TABLE MOTORIZATION (
  MOTOR VARCHAR(50) PRIMARY KEY,
  NUMBER_MOTORS INTEGER NOT NULL,
  MOTOR_TYPE VARCHAR(25) NOT NULL REFERENCES MOTOR_TYPE(TYPE),
  CRUISE_ALTITUDE DOUBLE PRECISION NOT NULL,
  CRUISE_SPEED DOUBLE PRECISION NOT NULL,
  TSFC DOUBLE PRECISION NOT NULL,
  LAPSE_RATE_FACTOR DOUBLE PRECISION NOT NULL,
  ID_THRUST_FUNCTION INTEGER NOT NULL REFERENCES THRUST_FUNCTION(ID_THRUST_FUNCTION)
);

CREATE TABLE AIRCRAFT_TYPE (
  TYPE VARCHAR(25) PRIMARY KEY
);

CREATE TABLE AIRCRAFT_MODEL (
  ID_AIRCRAFT_MODEL VARCHAR(25) PRIMARY KEY,
  DESCRIPTION VARCHAR(150) NOT NULL,
  MAKER VARCHAR(50) NOT NULL,
  AIRCRAFT_TYPE VARCHAR(25) NOT NULL REFERENCES AIRCRAFT_TYPE(TYPE),
  MOTOR VARCHAR(50) NOT NULL REFERENCES MOTORIZATION(MOTOR),
  EMPTY_WEIGHT DOUBLE PRECISION NOT NULL,
  MTOW DOUBLE PRECISION NOT NULL,
  MAX_PAYLOAD DOUBLE PRECISION NOT NULL,
  FUEL_CAPACITY DOUBLE PRECISION NOT NULL,
  VMO DOUBLE PRECISION NOT NULL,
  MMO DOUBLE PRECISION NOT NULL,
  WING_AREA DOUBLE PRECISION NOT NULL,
  WING_SPAN DOUBLE PRECISION NOT NULL,
  ASPECT_RATIO DOUBLE PRECISION NOT NULL,
  E DOUBLE PRECISION NOT NULL,
  ID_PROJECT INTEGER NOT NULL REFERENCES PROJECT(ID_PROJECT)
);

CREATE TABLE CDRAG_FUNCTION (
  CDRAG_0 DOUBLE PRECISION NOT NULL,
  SPEED DOUBLE PRECISION NOT NULL,
  ID_AIRCRAFT_MODEL VARCHAR(25) NOT NULL REFERENCES AIRCRAFT_MODEL(ID_AIRCRAFT_MODEL),
  CONSTRAINT PK_CDRAG_FUNCTION PRIMARY KEY (CDRAG_0, SPEED, ID_AIRCRAFT_MODEL)
);

CREATE TABLE SEGMENT (
  ID_SEGMENT VARCHAR(25) PRIMARY KEY,
  WIND_DIRECTION DOUBLE PRECISION NOT NULL,
  WIND_INTENSITY DOUBLE PRECISION NOT NULL,
  ALTITUDE DOUBLE PRECISION NOT NULL,
  ID_PROJECT INTEGER NOT NULL REFERENCES PROJECT(ID_PROJECT)
);

CREATE TABLE COORDINATE (
  ID_COORDINATE VARCHAR(25) PRIMARY KEY,
  LATITUDE DOUBLE PRECISION NOT NULL,
  LONGITUDE DOUBLE PRECISION NOT NULL,
  ID_PROJECT INTEGER NOT NULL REFERENCES PROJECT(ID_PROJECT)
);

CREATE TABLE AIRPORT (
  IATA CHAR(3) PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  TOWN VARCHAR(50) NOT NULL,
  COUNTRY VARCHAR(50) NOT NULL,
  ALTITUDE DOUBLE PRECISION,
  ID_COORDINATE VARCHAR(25) NOT NULL REFERENCES COORDINATE(ID_COORDINATE),
  ID_PROJECT INTEGER NOT NULL REFERENCES PROJECT(ID_PROJECT)
);

CREATE TABLE STOP (
  ID_STOP INTEGER PRIMARY KEY,
  IATA CHAR(3) NOT NULL REFERENCES AIRPORT(IATA),
  MIN_STOP_MINUTES INTEGER NOT NULL,
  DEPARTURE_TIME DATE NOT NULL,
  SCHEDULED_ARRIVAL DATE NOT NULL
);

CREATE TABLE AIRCRAFT (
  ID_AIRCRAFT INTEGER PRIMARY KEY,
  ID_AIRCRAFT_MODEL VARCHAR(25) NOT NULL REFERENCES AIRCRAFT_MODEL(ID_AIRCRAFT_MODEL),
  COMPANY VARCHAR(50) NOT NULL,
  MAX_CARGO DOUBLE PRECISION NOT NULL,
  MAX_CREW DOUBLE PRECISION NOT NULL
);

CREATE TABLE CLASS (
  ID_CLASS INTEGER NOT NULL,
  ID_AIRCRAFT INTEGER NOT NULL REFERENCES AIRCRAFT(ID_AIRCRAFT),
  MAX_NUMBER_PASSENGERS INTEGER NOT NULL,
  CONSTRAINT PK_CLAS PRIMARY KEY (ID_CLASS, ID_AIRCRAFT)
);

CREATE TABLE FLIGHT_TYPE (
  TYPE VARCHAR(25) PRIMARY KEY
);

CREATE TABLE FLIGHT_INFO (
  DESIGNATOR VARCHAR(7) PRIMARY KEY,
  ORIGIN_AIRPORT CHAR(3) NOT NULL REFERENCES AIRPORT(IATA),
  DEST_AIRPORT CHAR(3) NOT NULL REFERENCES AIRPORT(IATA),
  FLIGHT_TYPE VARCHAR(25) NOT NULL REFERENCES FLIGHT_TYPE(TYPE),
  ID_AICRAFT INTEGER NOT NULL REFERENCES AIRCRAFT(ID_AIRCRAFT),
  ID_PROJECT INTEGER NOT NULL REFERENCES PROJECT(ID_PROJECT)
);

CREATE TABLE FLIGHT_STOP (
  FLIGHT_INFO VARCHAR(7) NOT NULL REFERENCES FLIGHT_INFO(DESIGNATOR),
  ID_STOP INTEGER NOT NULL REFERENCES STOP(ID_STOP),
  CONSTRAINT PK_FLIGHT_STOP PRIMARY KEY (FLIGHT_INFO, ID_STOP)
);

CREATE TABLE WAYPOINT (
  ID_COORDINATE VARCHAR(25) NOT NULL REFERENCES COORDINATE(ID_COORDINATE),
  FLIGHT_INFO_DESIGNATOR VARCHAR(7) NOT NULL REFERENCES FLIGHT_INFO(DESIGNATOR),
  CONSTRAINT PK_WAYPOINT PRIMARY KEY (ID_COORDINATE, FLIGHT_INFO_DESIGNATOR)
);

CREATE TABLE FLIGHT_SIMULATION (
  ID_FLIGHT_SIMULATION INTEGER PRIMARY KEY,
  FLIGHT_INFO_DESIGNATOR VARCHAR(7) NOT NULL REFERENCES FLIGHT_INFO(DESIGNATOR),
  SCHEDULED_ARRIVAL DATE NOT NULL,
  DEPARTURE_DATE DATE NOT NULL,
  EFFECTIVE_CREW INTEGER NOT NULL,
  EFFECTIVE_CARGO DOUBLE PRECISION NOT NULL,
  EFFECTIVE_FUEL DOUBLE PRECISION NOT NULL,
  ID_PROJECT INTEGER NOT NULL REFERENCES PROJECT(ID_PROJECT)
);

CREATE TABLE AIRCRAFT_CLASS (
  ID_CLASS INTEGER NOT NULL,
  ID_AIRCRAFT INTEGER NOT NULL,
  ID_FLIGHT_SIMULATION INTEGER NOT NULL,
  NUMBER_PASSENGERS INTEGER NOT NULL,
  CONSTRAINT FK_AIRCRAFT_CLASS FOREIGN KEY (ID_CLASS, ID_AIRCRAFT) REFERENCES CLASS(ID_CLASS, ID_AIRCRAFT),
  CONSTRAINT PK_AIRCRAFT_CLASS PRIMARY KEY (ID_CLASS, ID_AIRCRAFT, ID_FLIGHT_SIMULATION)
);

CREATE TABLE FLIGHT_PLAN (
  ID_SEGMENT VARCHAR(25) NOT NULL REFERENCES SEGMENT(ID_SEGMENT),
  ID_FLIGHT_SIMULATION INTEGER NOT NULL REFERENCES FLIGHT_SIMULATION(ID_FLIGHT_SIMULATION),
  SEGMENT_ORDER INTEGER NOT NULL,
  CONSTRAINT PK_FLIGHT_PLAN PRIMARY KEY (ID_SEGMENT, ID_FLIGHT_SIMULATION)
);